---
deployment:
  tasks:
    - export DEPLOYPATH=/home3/wouessic/public_html
    - /bin/rm -rf $DEPLOYPATH/*
    - npm ci
    - npm run build
    - ls -la 
    - ls -la build/
    - /bin/cp -R build/* $DEPLOYPATH/
    - echo "Files now in public_html:"
    - ls -la $DEPLOYPATH/